### ISSUE TITLE
Do not clog history on lookup

### ISSUE THREAD

**Issue by MattiSG** [sgmap/verif.site#27]
`pushState` should be debounced to avoid storing every single keystroke.
![capture d ecran 2016-08-24 a 16 11 12 2](https://cloud.githubusercontent.com/assets/222463/17933745/8d78c644-6a15-11e6-8e64-13791333d809.png)

**Comment by ThibautGery** [comment]
Il est aussi possible d'utiliser [`replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method)
Support navigateur : [caniuse](http://caniuse.com/#search=replaceState)
