### ISSUE TITLE
Vérifier que l'accès SSH root@site.com est désactivé

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/verif.site#31]

**Comment by MattiSG** [comment]
Je ne vois pas comment on peut tester ça sans avoir les accès, SSH refuse de la même manière l'absence d'existence d'un compte et le fait de ne pas avoir la clé correspondante.

Je ferme, si je me suis trompé et qu'il y a un moyen technique de faire ça (@odtvince @jdesboeufs ?), ne pas hésiter à rouvrir.

**Comment by jdesboeufs** [comment]
On pourrait juste faire un nmap informatif qui liste les ports ouverts.
Le mar. 6 sept. 2016 à 11:39, Matti Schneider <notifications@github.com> a
écrit :
