### ISSUE TITLE
Ajouter des données de fréquentation

### ISSUE THREAD

**Issue by Flightan** [sgmap/verif.site#46]
La plupart de nos sites utilisent Piwik (http://stats.data.gouv.fr) qui propose une api de récupération des données. Est-ce intéressant de rajouter un badge sur le nombre de visiteur unique (J-1) ?

**Comment by MattiSG** [comment]
À mon avis on commence à s'éloigner beaucoup de la qualité de service HTTPS…

**Comment by Flightan** [comment]
Je pense que tu as raison et qu'en plus on aura jamais de traitement uniforme sur tout les sites testés.
Dans cette même logique, est-ce que le ration Uptime ne serait pas lui aussi de trop ?

**Comment by MattiSG** [comment]
C'est moins clair. Autant le nombre de visiteurs relève de l'usage et a une interprétation dépendante du contexte, autant la disponibilité me semble à maximiser sans équivoque. Je suis neutre sur le sujet.

**Comment by MattiSG** [comment]
En tous cas, sur « Ajouter des données de fréquentation », on est pour l'instant sur « Non », je ferme, ne pas hésiter à rouvrir si la question se pose à nouveau ou si désaccord  :)
