### ISSUE TITLE
Documenter l'ajout d'un nouveau site pour faciliter la collaboration

### ISSUE THREAD

**Issue by Flightan** [sgmap/verif.site#54]
Verbatim:

> je me suis permis de leur montrer verif.site ils seraient probablement intéressés pour ajouter quelques uns de leurs endpoints à monitorer
> je leur ai montré http://verif.site et le github, mais je n’ai pas trouvé de doc pour les aider à faire une PR pour proposer leurs sites

**Comment by MattiSG** [comment]
À mettre dans un `CONTRIBUTING.md`.
